# Generated by Django 5.1.4 on 2025-01-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
