# Generated by Django 5.1.4 on 2025-01-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0004_alter_docteur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteur',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
