# Generated by Django 5.1.4 on 2025-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur', '0005_alter_docteur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docteur',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
